POST http://localhost:3333/habits
Content-Type: application/json

{
  "title": "Exemplo",
  "weekDays": [0,1,4]
}

###
GET http://localhost:3333/day?date=2023-12-21T03%3A00%3A00.000z

###
PATCH http://localhost:3333/habits/fa1a1bcf-3d87-4626-8c0d-d7fd1255ac00/toggle


###
GET http://localhost:3333/summary